name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: docker/login-action@v1
        with:
          registry: 085895507678.dkr.ecr.us-west-2.amazonaws.com/docker-login-test
          username: ${{ secrets.AWS_ACCESS_KEY }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: latest
          
